-- ============================================================
-- Dental Clinic GT — MySQL schema for cloud9.ge hosting
-- Run once in cPanel → phpMyAdmin → (your database) → SQL.
-- Safe to run on a fresh database. All times are Tbilisi local
-- (Georgia has no daylight saving, so no timezone juggling).
-- ============================================================

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS services (
  id           VARCHAR(64)  NOT NULL PRIMARY KEY,
  name_ka      VARCHAR(200) NOT NULL,
  name_en      VARCHAR(200) NOT NULL,
  duration_min INT          NOT NULL DEFAULT 30,
  price_from   INT          NULL,
  price_to     INT          NULL,
  sort         INT          NOT NULL DEFAULT 0,
  active       TINYINT(1)   NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS doctors (
  id      CHAR(36)     NOT NULL PRIMARY KEY,   -- uuid, generated by the API
  slug    VARCHAR(64)  NULL UNIQUE,
  name    VARCHAR(200) NOT NULL,
  role_ka VARCHAR(200) NULL,
  role_en VARCHAR(200) NULL,
  active  TINYINT(1)   NOT NULL DEFAULT 1,
  sort    INT          NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS doctor_services (
  doctor_id  CHAR(36)    NOT NULL,
  service_id VARCHAR(64) NOT NULL,
  PRIMARY KEY (doctor_id, service_id),
  CONSTRAINT fk_ds_doctor  FOREIGN KEY (doctor_id)  REFERENCES doctors(id)  ON DELETE CASCADE,
  CONSTRAINT fk_ds_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS working_hours (
  id        BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  doctor_id CHAR(36) NOT NULL,
  weekday   TINYINT  NOT NULL,              -- 0=Sun .. 6=Sat
  start_min INT      NOT NULL,              -- minutes from midnight (600 = 10:00)
  end_min   INT      NOT NULL,
  CONSTRAINT fk_wh_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
  CHECK (weekday BETWEEN 0 AND 6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS appointments (
  id            BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  doctor_id     CHAR(36)     NOT NULL,
  service_id    VARCHAR(64)  NOT NULL,
  starts_at     DATETIME     NOT NULL,       -- Tbilisi local time
  ends_at       DATETIME     NOT NULL,
  patient_name  VARCHAR(200) NOT NULL,
  patient_phone VARCHAR(50)  NOT NULL,
  patient_email VARCHAR(200) NULL,
  note          TEXT         NULL,
  channel       VARCHAR(20)  NOT NULL DEFAULT 'online',   -- online|phone|messenger|walkin
  status        VARCHAR(20)  NOT NULL DEFAULT 'booked',   -- booked|done|cancelled
  payments      JSON         NULL,           -- [{"method":"tbc","amount":150}, ...]
  reminded_at   DATETIME     NULL,           -- day-before SMS already sent
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_doctor_start (doctor_id, starts_at),      -- hard stop for double-booking
  KEY idx_starts (starts_at),
  CONSTRAINT fk_ap_doctor  FOREIGN KEY (doctor_id)  REFERENCES doctors(id)  ON DELETE CASCADE,
  CONSTRAINT fk_ap_service FOREIGN KEY (service_id) REFERENCES services(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_users (
  id            INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email         VARCHAR(200) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  active        TINYINT(1)   NOT NULL DEFAULT 1,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Editable site texts & photo versions (admin "საიტი" tab).
-- Keys look like 'ka:hero_title' / 'en:hero_title' / 'img_ver_hero'.
-- A missing key means the site shows its built-in default text.
CREATE TABLE IF NOT EXISTS site_content (
  k VARCHAR(100) NOT NULL PRIMARY KEY,
  v TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Brute-force protection for the admin login
CREATE TABLE IF NOT EXISTS login_attempts (
  id           BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ip           VARCHAR(64) NOT NULL,
  attempted_at DATETIME    NOT NULL,
  KEY idx_ip_time (ip, attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------- Seed: the service catalog (same as the live site) ----------
INSERT IGNORE INTO services (id, name_ka, name_en, duration_min, price_from, price_to, sort) VALUES
  ('general',   'ზოგადი სტომატოლოგია',     'General dentistry',     30,   50,  450, 1),
  ('implants',  'იმპლანტაცია',             'Dental implants',       60, 1500, 3000, 2),
  ('ortho',     'ორთოდონტია',              'Orthodontics',          45, 2000, 7000, 3),
  ('cosmetic',  'ესთეტიკა და გათეთრება',   'Cosmetic & whitening',  45,  300, 1200, 4),
  ('pediatric', 'ბავშვთა სტომატოლოგია',    'Pediatric dentistry',   30,   50,  150, 5),
  ('surgery',   'ქირურგია და პროთეზირება', 'Surgery & prosthetics', 60,   60, 1500, 6);

-- Doctors, working hours and existing appointments are brought over from
-- the old database — see docs/DEPLOY-CLOUD9.md, step "მონაცემების გადმოტანა".
